version: '3.9'

services:        
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Change this to a secure password
      MYSQL_DATABASE: my_database # Change this to the name of your database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password # Change this to the same password as in the db service
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
